version: '3'
services:
  hello-bot-server:
    container_name: hello-bot-server
    build:
      context: .
    image:
      hello-bot-server:latest
    volumes:
      - /etc/ssl/mycerts:/etc/ssl/mycerts
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_CERT=${WEBHOOK_CERT}
      - WEBHOOK_INTERNALURL=${WEBHOOK_INTERNALURL}
  nginx-server:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/mycerts:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
